// Generated by Selenium IDE
package testiranje;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.logging.Logger;
import java.io.FileWriter;
import java.net.MalformedURLException;
import java.net.URL;
public class FacebookTest {
	private Logger l = Logger.getLogger(KorpaTest.class.getName());
	private String exePath="C:\\Users\\mjedor\\Desktop\\chromedriver_win32\\chromedriver.exe";
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  System.setProperty("webdriver.chrome.driver", exePath);
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void facebook() throws InterruptedException {
    driver.get("https://coral.rs/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".fa-facebook-square")).click();
    vars.put("win5534", waitForWindow(2000));
    driver.switchTo().window(vars.get("win5534").toString());
    Thread.sleep(4000);
    assertEquals(driver.getCurrentUrl(),"https://www.facebook.com/coral.computers/?notif_t=page_fan");
    
    String string ="\nNaziv testa : Facebook test \n"+
            "Opis testa: Proveravanje linka prema Facebook stranici \n"+
  "\nTest je uspesan \n\n";
    l.info(string.toString());
    
 try {
 	FileWriter fw = new FileWriter("C:\\Users\\mjedor\\Desktop\\CoralTesting\\test-report.txt", true);
 	fw.write(string.toString());
 	fw.flush();
 	fw.close();
 }catch (Exception e) {
 	System.out.println(e.getMessage());
 }
  }
}
