// Generated by Selenium IDE
package testiranje;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.logging.Logger;
import java.io.FileWriter;
import java.net.MalformedURLException;
import java.net.URL;
public class RegisterTest {
	private Logger l = Logger.getLogger(KorpaTest.class.getName());
	private String exePath="C:\\Users\\mjedor\\Desktop\\chromedriver_win32\\chromedriver.exe";
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  System.setProperty("webdriver.chrome.driver", exePath);
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void register() {
    driver.get("https://coral.rs/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.cssSelector(".menu-sec span")).click();
    driver.findElement(By.id("reg_username")).click();
    driver.findElement(By.id("reg_username")).sendKeys("Test1221");
    driver.findElement(By.id("reg_email")).click();
    driver.findElement(By.id("reg_email")).sendKeys("testsajt1221@gmail.com");
    driver.findElement(By.id("reg_password")).click();
    driver.findElement(By.id("reg_password")).sendKeys("testsajt1221");
    driver.findElement(By.name("register")).click();
    
    WebElement poruka = driver.findElement(By.xpath("//*[@id=\"modernizrcom\"]/body/div[2]/div[1]/div/div/div/div[1]/ul/li"));
    String reg = poruka.getText();
    assertEquals(poruka.getText(),"Error: An account is already registered with your email address. Please log in.");
    String string ="\nNaziv testa : Register test \n"+
            "Opis testa: Registrovanje korisnika\n"+
  "\nTest je uspesan \n\n";
    l.info(string.toString());
    
    try {
     	FileWriter fw = new FileWriter("C:\\Users\\mjedor\\Desktop\\CoralTesting\\test-report.txt", true);
     	fw.write(string.toString());
     	fw.flush();
     	fw.close();
     }catch (Exception e) {
     	System.out.println(e.getMessage());
    
     }
  }
}
