// Generated by Selenium IDE
package testiranje;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.logging.Logger;
import java.io.FileWriter;
import java.net.MalformedURLException;
import java.net.URL;
public class StraniceTest {
	private Logger l = Logger.getLogger(KorpaTest.class.getName());
	private String exePath="C:\\Users\\mjedor\\Desktop\\chromedriver_win32\\chromedriver.exe";
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  System.setProperty("webdriver.chrome.driver", exePath);
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void stranice() {
	double v1 = System.currentTimeMillis();
    driver.get("https://coral.rs/");
    double t1 = System.currentTimeMillis();
	double r1= t1 - v1;
	System.out.println(r1);
    driver.manage().window().setSize(new Dimension(1920, 1040));
    driver.findElement(By.cssSelector(".menu-sec span")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("testsajt1221@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("testsajt1221");
    driver.findElement(By.name("login")).click();
    driver.findElement(By.linkText("Coral Computers")).click();
    
    driver.findElement(By.linkText("Kontakt")).click();
    double t2 = System.currentTimeMillis();
	double r2= t2 - t1;
	System.out.println(r2);
	
    driver.findElement(By.linkText("O nama")).click();
	double t3 = System.currentTimeMillis();
	double r3= t3 - t2;
	System.out.println(r3);
	
    driver.findElement(By.linkText("Dostava")).click();
	double t4 = System.currentTimeMillis();
	double r4= t4 - t3;
	System.out.println(r4);
	
    driver.findElement(By.linkText("Cenovnik")).click();
	double t5 = System.currentTimeMillis();
	double r5= t5 - t4;
	System.out.println(r5);
	
    driver.findElement(By.linkText("Garancija")).click();   
    double t6 = System.currentTimeMillis();
	double r6= t6 - t5;
	System.out.println(r6);
	
	double sv = (r1 + r2 + r3 + r4 + r5 + r6)/6;
	System.out.println("Srednja vrednost: " + sv);
	
	String string ="\nIme testa : Stranice test \n"+
	        "Opis testa: Performanse otvaranja razlicitih stranica i prikaz njihovog proseka\r\n" + 
	        "Vremena pokretanja sajtova u milisekundama: \n"+
	        r1 + "\n" +
    		r2 + "\n" +
    		r3 + "\n" +
    		r4 + "\n" +
    		r5 + "\n" +
    		r6 + "\n" +
    		"Srednja vrednost pokretanja stranica: \t" +
    		sv +
	"\n\nTest je uspesan \n\n";
	
	l.info(string.toString());
	try {
	 	FileWriter fw = new FileWriter("C:\\Users\\mjedor\\Desktop\\CoralTesting\\test-report.txt", true);
	 	fw.write(string.toString());
	 	fw.flush();
	 	fw.close();
	 }catch (Exception e) {
	 	System.out.println(e.getMessage());
	 }
  }
}
