// Generated by Selenium IDE
package testiranje;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.logging.Logger;
import java.io.FileWriter;
import java.net.MalformedURLException;
import java.net.URL;
public class UkupnaCenaTest {
	private Logger l = Logger.getLogger(KorpaTest.class.getName());
	private String exePath="C:\\Users\\mjedor\\Desktop\\chromedriver_win32\\chromedriver.exe";
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  System.setProperty("webdriver.chrome.driver", exePath);
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void ukupnaCena() throws InterruptedException {
    driver.get("https://coral.rs/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.cssSelector(".menu-sec span")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("testsajt1221@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("testsajt1221");
    driver.findElement(By.name("login")).click();
    driver.findElement(By.linkText("Coral Computers")).click();
    driver.findElement(By.linkText("Monitori")).click();
    driver.findElement(By.cssSelector("#\\36 8032 .attachment-medium")).click();
    driver.findElement(By.cssSelector(".single_add_to_cart_button")).click();
    driver.findElement(By.cssSelector(".wc-forward")).click();
    driver.findElement(By.cssSelector(".woocommerce-cart-form__cart-item:nth-child(4) .remove")).click();
  
    Thread.sleep(4000);

    WebElement cena1 = driver.findElement(By.xpath("//*[@id=\"modernizrcom\"]/body/div[2]/div[1]/div/div/div/form/table/tbody/tr[1]/td[4]/span/bdi"));
    WebElement cena2 = driver.findElement(By.xpath("//*[@id=\"modernizrcom\"]/body/div[2]/div[1]/div/div/div/form/table/tbody/tr[2]/td[4]/span/bdi"));
    WebElement cena3 = driver.findElement(By.xpath("//*[@id=\"modernizrcom\"]/body/div[2]/div[1]/div/div/div/form/table/tbody/tr[3]/td[4]/span/bdi"));
    WebElement zbir = driver.findElement(By.xpath("//*[@id=\"modernizrcom\"]/body/div[2]/div[1]/div/div/div/div[2]/div/table/tbody/tr[1]/td/span/bdi"));
    
    String p1 = cena1.getText();
    p1 = p1.replace(" din", "");
    p1 = p1.replace(",", "");
    String p2 = cena2.getText();
    p2 = p2.replace(" din", "");
    p2 = p2.replace(",", "");
    String p3 = cena3.getText();
    p3 = p3.replace(" din", "");
    p3 = p3.replace(",", "");
    
    Double c1 = Double.valueOf(p1);
    Double c2 = Double.valueOf(p2);
    Double c3 = Double.valueOf(p3);
    Double uc = c1+c2+c3;
    
    String ukupno = zbir.getText();
    String u = zbir.getText();
    u = u.replace(" din", "");
    u = u.replace(",","");
    u = u.replace(","," (oslobodjeno PDV-a)");
    Double konacno = Double.valueOf(u);
    assertEquals(konacno,uc);
    String string ="\nIme testa : Ukupna cena \n"+
            "Opis testa: Proveravanje ukupne cene\n"+
    		"Ukupna cena je: " +
    		ukupno.toString() +
     "\n\nTest je uspesan \n\n";
    l.info(string.toString());
    
    try {
     	FileWriter fw = new FileWriter("C:\\Users\\mjedor\\Desktop\\CoralTesting\\test-report.txt", true);
     	fw.write(string.toString());
     	fw.flush();
     	fw.close();
     }catch (Exception e) {
     	System.out.println(e.getMessage());
     }
  }
}
